package com.iu.studytracker.data.database.entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * A scheduled study task — one topic assigned to one calendar day.
 *
 * Generated by the [TopicScheduler] algorithm after the user completes
 * monthly setup. Each task links back to its source [Topic] and the
 * parent [MonthPlan], and tracks whether the user has completed it.
 *
 * [scheduledDate] is stored as "yyyy-MM-dd" string for easy querying
 * and human readability.
 */
@Entity(
    tableName = "daily_tasks",
    foreignKeys = [
        ForeignKey(
            entity = MonthPlan::class,
            parentColumns = ["id"],
            childColumns = ["monthPlanId"],
            onDelete = ForeignKey.CASCADE
        ),
        ForeignKey(
            entity = Topic::class,
            parentColumns = ["id"],
            childColumns = ["topicId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [
        Index(value = ["monthPlanId"]),
        Index(value = ["topicId"]),
        Index(value = ["scheduledDate"])
    ]
)
data class DailyTask(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    /** FK → month_plans.id */
    val monthPlanId: Long,

    /** FK → topics.id */
    val topicId: Long,

    /** Calendar date in "yyyy-MM-dd" format, e.g. "2026-08-15" */
    val scheduledDate: String,

    /** Whether the user has marked this task as done */
    val isCompleted: Boolean = false,

    /** Epoch millis when completed, null if not yet done */
    val completedAt: Long? = null,

    /** Expected time to complete in minutes (default 25 for one Pomodoro) */
    val estimatedMinutes: Int = 25,

    /** Actual time spent focusing on this task */
    val actualMinutesSpent: Int = 0
)
